sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        ignore_exceptions:
            - "Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException"
            - "Symfony\\Component\\HttpKernel\\Exception\\ConflictHttpException"
            - "Symfony\\Component\\Validator\\Exception\\ValidationFailedException"
