networks:
    kalaxia:
        driver: bridge

volumes:
    db-data:
    rabbitmq-data:
    redis-data:
    caddy_data:
    caddy_config:
    mercure_data:
    mercure_config:

services:
    phpfpm:
        container_name: kalaxia_app
        build: docker/fpm
        user: www-data
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
        volumes:
            - "./:/srv/app"
        networks:
            - kalaxia

    mariadb:
        container_name: kalaxia_mariadb
        image: mariadb:10
        environment:
            MARIADB_DATABASE: ${MARIADB_DATABASE:-kalaxia_game}
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-kalaxia}
            MARIADB_USER: ${MARIADB_USER:-kalaxia}
            MARIADB_PASSWORD: ${MARIADB_PASSWORD:-kalaxia}
        networks:
            - kalaxia
        volumes:
            # mysql
            - db-data:/var/lib/mysql

    redis:
        container_name: kalaxia_redis
        image: redis
        networks:
            - kalaxia

    rabbitmq:
        container_name: kalaxia_rabbitmq
        image: rabbitmq:3.9-management-alpine
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 30s
            timeout: 30s
            retries: 3
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq
        networks:
            - kalaxia

    caddy:
        container_name: kalaxia_caddy_webserver
        image: caddy
        depends_on:
            phpfpm:
                condition: service_started
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - './docker/caddy/Caddyfile:/etc/caddy/Caddyfile'
            - './:/srv/app'
            - './var/log/caddy/:/var/log/caddy'
            - caddy_data:/data
            - caddy_config:/config
        networks:
            - kalaxia

    supervisord:
        container_name: kalaxia_worker
        build: docker/supervisord
        user: www-data
        depends_on:
            rabbitmq:
                condition: service_healthy
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
        volumes:
            - "./:/srv/app"
            - "./var/logs/supervisord/:/var/log/supervisord/"
            - "./supervisord.conf:/etc/supervisor/supervisord.conf"
        networks:
            - kalaxia

    mercure:
        container_name: kalaxia_mercure
        image: dunglas/mercure
        restart: unless-stopped
        environment:
          # Uncomment the following line to disable HTTPS,
          SERVER_NAME: ':80'
          #SERVER_NAME: 'mercure.kalaxia.local'
          # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
        # Comment the following line to disable the development mode
        healthcheck:
          test: ["CMD", "wget", "-q", "--spider", "https://localhost/healthz"]
          timeout: 5s
          retries: 5
          start_period: 60s
        networks:
            - kalaxia
        volumes:
          - mercure_data:/data
          - mercure_config:/config
        ports:
            - '80'
