financial:
    resource: './athena/financial.yaml'
    prefix: /financial

trade:
    resource: './athena/trade.yaml'
    prefix: /trade

switchplanet:
    path: /switchplanet/{planetId}/{page}
    controller: App\Modules\Athena\Infrastructure\Controller\Base\SwitchPlanet
    methods: 'GET'
    defaults:
        page: 'current'

base_overview:
    path: /overview
    controller: App\Modules\Athena\Infrastructure\Controller\Base\ViewOverview

change_base_type:
    path: /change-planet-type
    controller: App\Modules\Athena\Infrastructure\Controller\Base\ChangePlanetType

leave_planet:
    path: /leave-planet
    controller: App\Modules\Athena\Infrastructure\Controller\Base\LeavePlanet

rename_planet:
    path: /rename-planet
    controller: App\Modules\Athena\Infrastructure\Controller\Base\RenamePlanet
    methods: 'POST'

create_recycling_mission:
    path: /recycling-missions/create/{targetId}
    controller: App\Modules\Athena\Infrastructure\Controller\Recycling\CreateMission
    methods: 'POST'

add_recyclers_to_mission:
    path: /recycling-missions/{id}/add-recyclers
    controller: App\Modules\Athena\Infrastructure\Controller\Recycling\AddToMission
    methods: 'POST'

cancel_recycling_mission:
    path: /recycling-missions/{id}/cancel
    controller: App\Modules\Athena\Infrastructure\Controller\Recycling\CancelMission

recycle_ships:
    path: /ships/recycle
    controller: App\Modules\Athena\Infrastructure\Controller\Ship\Recycle

build_ships:
    path: /ships/build
    methods: ['POST']
    controller: App\Modules\Athena\Infrastructure\Controller\Ship\BuildShips

load_ship_panel:
    path: /ships/{shipNumber}/panel
    controller: App\Modules\Athena\Infrastructure\Controller\Ship\ViewShipPanel

cancel_ship_queue:
    path: /ship-queues/{id}/cancel
    controller: App\Modules\Athena\Infrastructure\Controller\Ship\CancelQueue

autocomplete_planet:
    path: /api/planets/{search}
    controller: App\Modules\Athena\Infrastructure\Controller\Base\AutocompletePlanet
